### ISSUE TITLE
[Feat] 사용자 닉네임 저장 API

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#127]
![i14238921319](https://github.com/GunGonGamLee/ft_transcendence/assets/90092181/c84d8f27-e579-4914-b092-f1989d2b542c)

사용자의 닉네임을 저장하는 API를 구현합니다.
<br>
`/api/users/nickname`

## TODO
- [x] jwt 토큰 검증
- [x] 닉네임 중복 확인
- [x] 중복이 아닐 경우 디비에 저장
- [x] swagger 작성
- [x] 아바타 설정하기

**Comment by LWJ0513** [comment]
엇.. 닉네임을 설정할 때 아바타도 저장해야 한다@!!!!
