### ISSUE TITLE
[Feat] 사용자 지정 게임방 생성 API

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#143]
![](https://t1.daumcdn.net/cafeattach/1IHuH/8b1a113f384dbcbcffab1e91511105922393e613)
<br>
사용자 지정 게임방 생성을 만든다!!
`/api/games`
<br>
## Request body
| name | value | description |
|-------|-------|-------|
| title | string | 게임방 이름 |
| password | string | 비밀번호 |
| mode | num | 게임 모드 |

mode = casual_1vs1 : 1대1
mode = casual_tournament : 토너먼트
mode = rank

비밀번호 없으면 password = ""
방장은 jwt로 확인
<br>
## RESPONSE
- 성공 시: Http status code 201
- 방 이름 중복 시, mode 잘못 들어왔을 때 : 400
- jwt 인증 실패 : 401
- 없는 유저일 때 : 404
- 방 생성 실패 시: 500 -> 뜨면 망하는디
<br>

## TODO
- [x] jwt 검증
- [x] 방 이름 중복 검사
- [x] 들어온 데이터를 토대로 디비 값 추가
   - [x] 제목
   - [x] 비번
   - [x] 상태
   - [x] 모드
   - [x] 방장
- [x] swagger

## 생각하기 
- [x] result 를 미리 만들어 저장할 것인가 ? 경기가 끝난 뒤 저장 연결?
   -> 어차피 미리 만들어봤자 넣을 값도 없는데 그냥 나중에 경기 끝나고 값 들어오거나 게임 시작으로 매칭됐을 때 생각하자
- [ ] 다른 방에도 똑같은 사람이 있는지 검사를 해야하나? 프론트에서 소켓으로 동시접속 막을거긴 한데 ..

**Comment by LWJ0513** [comment]
리턴하는 걸 깜빡했긔
