### ISSUE TITLE
[Feat] 게임방 입장 API 

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#168]
![](https://m1.daumcdn.net/cfile269/image/2629483B588D83B12271C6)

게임방 입장 API 를 구현합니다~
```
POST
/api/games/{game_id}
``` 
<br>

## Request
jwt
신속히 입장시 game_id = 0
<br>
## Response body
- [x] 방 제목
- [x] 방 비밀번호
- [x] 방 모드
   - mode = local_tournament : 로컬 토너먼트
   - mode = casual_1vs1 : 1대1
   - mode = casual_tournament : 토너먼트
   - mode = rank
- [x] 현재 방에 들어가있는 사용자의 정보
  - [x] 닉네임
  - [x] 프로필
  - [x] 레이팅
  - [x] 방장 여부
<br>

## TODO
- [x] 트렌젝션 관리!!!!
- [x] jwt 토큰 유효성 검사 401, 404
- [x] game_id 유효성 검사(숫자 아니면.. 아웃) 400
- [x] game_id=0 일 때 (신속히 랜덤 입장)(status는 view table에서 걸러진다)
   - [x] 생성되어 있는 방이 없으면 방을 만들어야 한다. -> 201 (response body??)
   - [x] 생성되어 있는 아무 방에 들어간다 -> 200 (response body???)
- [x] 유효한 방인지 검사
   - [x] status가 0이 아닌 방 400
   - [x] 없는 id 404
- [x] 제대로 된 방이면
   - [x]  인원 수 확인 
      - [x] 입장 실패(동시에 누가 들어와 꽉참) : 409
      - [x] 입장 성공 db에 player 추가 200
- [x] swagger

## 생각하깅
- [x] response body 어떻게 해??????? 어느 방에 들어갔는지 알려줘야 하는 거 아니야? 그 방에 누가 있는지는 어케 알지? 소켓연결은?

**Comment by LWJ0513** [comment]
모드 확인을 안 한다 
1ㄷ1이면 최대 두 명인지 확인해야 돼

**Comment by LWJ0513** [comment]
웹소켓 api로 바꿔야 돼요
