### ISSUE TITLE
[Feat] 랭크 참가 API 

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#181]
![](https://m1.daumcdn.net/cfile286/image/2217914B58954C2801E650)
<br>
랭크 참가 API 를 구현합니다.
```
/api/games/rank
``` 

## Request
jwt

## Response body
- 방 제목
- 방 비밀번호
- 방 모드
- 현재 방에 들어가있는 사용자의 정보
  - 닉네임
  - 아바타
  - 레이팅
  - 방장 여부

## TODO
- [ ] 신속히 입장도 생성되어 있는 방이 없으면 방을 만들어야 한다 -> 201
- [ ] 들어갈 때 인원수를 확인한다.
- [ ] 트렌젝션 관리 해야 한다.
