### ISSUE TITLE
[Feat] 게임방 퇴장 API

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#183]
![](https://m1.daumcdn.net/cfile255/image/263E704C58954C380B0504)
<br>
게임방 퇴장 API 를 구현합니다
근데 이제 소켓으로 사용하기 때문에 소켓이 disconnect 되었을 때의 처리입니다.
```
/api/games/{game_id}
``` 
<br>

## Request
socket이 disconnect

## Response
- 에러 발생시 json key : error
- 정상적인 json key : data (방에 남아있는 애들한테)
<br>

## TODO
방장이 퇴장할 경우 백엔드에서 임의로 한 명을 방장으로 선임.
선임 후 response body로 방장에 대한 정보를 줘야 함.

- [x] 먼저 모드를 확인한다. 
- [x] 방장 검사를 casual mode일 때만 함
- [x] 방장이 아닌 사람이 성공적으로 퇴장
- [x] 방장이 성공적으로 퇴장: 200 + response body{ "manager" : "nickname"}
- [x] 전부 다 나가면 delete
