### ISSUE TITLE
[Feat] 게임 시작

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#312]
![](https://i.imgur.com/IWXpOK5.gif)
<br>

# 게임 시작 전

## 커스텀 토너먼트
1. 게임 시작 버튼이 눌림 (프론트)
2. 프론트가 백 웹소켓으로 -> 메세지를 보냄
   ```
   'type' : 'game_start',
   'data' : 'true'
   ```
3. 백엔드가 메세지를 받으면 프론트에게 요청 보낼 웹소켓의 주소를 담은 메세지를 보냄
   ```
   {url: "/ws/games/start/88/"}
   ```
   -> `"wss://localhost/ws/games/start/{game_id}/"`

4. 프론트가 기존 소켓을 끊고, 받은 주소로 새로운 소켓 요청을 보낸다.

<br>

## 랭크 토너먼트
1. 큐가 잡히면 백이 프론트에게 요청 보낼 웹소켓의 주소를 담은 메세지를 보냄
   - `"url" : "wss://localhost/ws/games/start/{game_id}/"`
2. 프론트가 기존 소켓을 끊고, 받은 주소로 새로운 소켓 요청을 보낸다.

<br>

---

# 게임 시작 

## 게임 요청 후 첫 메세지 (매칭 화면 그리기용)
1ㄷ1
```json
# 'type': 'game_info'
{
    "data": {
           "match1": [
                 {"nickname": "원림", "avatar": "yoda.png", "rating": 3343}, 
                 {"nickname": "원정", "avatar": "han_solo.png", "rating": 321}
          ]
       }
}
```

<br>

```javascript
// 5초 후 겜 시작 메세지
ws.send(JSON.stringify({
   type: "start",
   data: {
      map_width: 1920,
      map_height: 1080
    },
}),);
```

<br>

## 인게임
게임은 5번째 판이 끝나면 끝난다.

### 키보드 입력시
프론트가 백으로 보내는 소켓 메세지
```
{
    'type' : 'keyboard',
    'data' : 'up'
}
```
```
{
    'type' : 'keyboard',
    'data' : 'down'
}
```
<br>

### 백이 보내는 메세지
화면을 그리기 위한 정보, 1초에 24번 보낸다
```
{
    'type' : 'game_data',
    'data' : { ?? }
}
```

<br>

### 게임 끝났을 때
1. pvp면
   - 둘 다 게임 전적 페이지로 리다이렉트 (이 전 처리 어떻게 할 지 생각하기)
2. match1 이 먼저 끝난 경우 
   - 디비 저장
   - 패배한 사람은 전적페이지로 이동
   - 승리한 사람에게 waiting 관련 socket message 전송
3. match2가 이후에 끝났을 때
   - 디비 저장
   - 패배한 사람은 전적페이지로 이동
   - match2 승리한 사람이랑 Match1 애랑 새로운 게임 시작 (이거 메세지 어떻게 할 지 정해야 됨)

<br>

## TODO
1. 소켓 연결 요청이 들어온다
- [x] 유저 검증
- [x] 모드 확인
   - 1ㄷ1 이면
      - [x] 그냥 match1에 매칭
      - [x] result db 생성, game - match1 에 저장
   - 토너먼트면
      - [x] 포지션 확인하고 둘둘 match1, match2 에 지정
      - [x] result db 생성, game - match1, match2 에 저장
- [x] return 매칭 정보, 아바타, 점수, 닉네임
- [ ] game 생성
