### ISSUE TITLE
[Feat] 42 로그인 구현

### ISSUE THREAD

**Issue by LWJ0513** [GunGonGamLee/ft_transcendence#71]
![철푸덕](https://github.com/GunGonGamLee/ft_transcendence/assets/90092181/01ebfbe5-00b9-44d4-a73c-e940cf275aae)

42 Oauth2.0 로그인을 구현한다.
<br>

## TODO
- [x] 42 로그인 페이지로 리다이렉션
- [x] callback 함수로 code 발급
- [x] access token 발급
- [x] 42 api 로 사용자 정보 얻어오기
- [x] 사용자 정보 DB에 저장하기
---
- [x] 이메일 전송
- [x] 1차 JWT 발급
- [ ] 2차 인증 코드 입력창으로 이동
- [ ] 2차 인증 코드 다시 받기 API 구현
- [ ] 받아온 인증 코드 검증
- [ ] refresh token db에 저장?
- [ ] 이메일에서 잘라온 username을 지워야 합니다~
위의 체크 안 된 부분들은 #89 로 넘어갔습니다.
